src/java/com/jean/jsf/DireccionController.java
package com.jean.jsf;

import com.jean.jpa.Direccion;
import com.jean.jsf.util.JsfUtil;
import com.jean.jsf.util.PaginationHelper;
import com.jean.jpacontroller.DireccionFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "direccionController")
@SessionScoped
public class DireccionController implements Serializable {

    private Direccion current;
    private DataModel items = null;
    @EJB
    private com.jean.jpacontroller.DireccionFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public DireccionController() {
    }

    public Direccion getSelected() {
        if (current == null) {
            current = new Direccion();
            selectedItemIndex = -1;
        }
        return current;
    }

    private DireccionFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Direccion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Direccion();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DireccionCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Direccion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DireccionUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Direccion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("DireccionDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Direccion.class)
    public static class DireccionControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DireccionController controller = (DireccionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "direccionController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Direccion) {
                Direccion o = (Direccion) object;
                return getStringKey(o.getDireccionId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Direccion.class.getName());
            }
        }
    }
}

web/direccion/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateDireccionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_direccionId}" for="direccionId" />
                    <h:inputText id="direccionId" value="#{direccionController.selected.direccionId}" title="#{bundle.CreateDireccionTitle_direccionId}" required="true" requiredMessage="#{bundle.CreateDireccionRequiredMessage_direccionId}"/>
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_direcLinea1}" for="direcLinea1" />
                    <h:inputText id="direcLinea1" value="#{direccionController.selected.direcLinea1}" title="#{bundle.CreateDireccionTitle_direcLinea1}" />
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_direcLinea2}" for="direcLinea2" />
                    <h:inputText id="direcLinea2" value="#{direccionController.selected.direcLinea2}" title="#{bundle.CreateDireccionTitle_direcLinea2}" />
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_ciudad}" for="ciudad" />
                    <h:inputText id="ciudad" value="#{direccionController.selected.ciudad}" title="#{bundle.CreateDireccionTitle_ciudad}" />
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_cp}" for="cp" />
                    <h:inputText id="cp" value="#{direccionController.selected.cp}" title="#{bundle.CreateDireccionTitle_cp}" />
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_esProvId}" for="esProvId" />
                    <h:selectOneMenu id="esProvId" value="#{direccionController.selected.esProvId}" title="#{bundle.CreateDireccionTitle_esProvId}" >
                        <f:selectItems value="#{esProvController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_direccionTypeId}" for="direccionTypeId" />
                    <h:selectOneMenu id="direccionTypeId" value="#{direccionController.selected.direccionTypeId}" title="#{bundle.CreateDireccionTitle_direccionTypeId}" >
                        <f:selectItems value="#{direccionTypeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateDireccionLabel_alumnoId}" for="alumnoId" />
                    <h:selectOneMenu id="alumnoId" value="#{direccionController.selected.alumnoId}" title="#{bundle.CreateDireccionTitle_alumnoId}" >
                        <f:selectItems value="#{alumnoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{direccionController.create}" value="#{bundle.CreateDireccionSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{direccionController.prepareList}" value="#{bundle.CreateDireccionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateDireccionIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/direccion/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditDireccionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditDireccionLabel_direccionId}" for="direccionId" />
                    <h:inputText id="direccionId" value="#{direccionController.selected.direccionId}" title="#{bundle.EditDireccionTitle_direccionId}" required="true" requiredMessage="#{bundle.EditDireccionRequiredMessage_direccionId}"/>
                    <h:outputLabel value="#{bundle.EditDireccionLabel_direcLinea1}" for="direcLinea1" />
                    <h:inputText id="direcLinea1" value="#{direccionController.selected.direcLinea1}" title="#{bundle.EditDireccionTitle_direcLinea1}" />
                    <h:outputLabel value="#{bundle.EditDireccionLabel_direcLinea2}" for="direcLinea2" />
                    <h:inputText id="direcLinea2" value="#{direccionController.selected.direcLinea2}" title="#{bundle.EditDireccionTitle_direcLinea2}" />
                    <h:outputLabel value="#{bundle.EditDireccionLabel_ciudad}" for="ciudad" />
                    <h:inputText id="ciudad" value="#{direccionController.selected.ciudad}" title="#{bundle.EditDireccionTitle_ciudad}" />
                    <h:outputLabel value="#{bundle.EditDireccionLabel_cp}" for="cp" />
                    <h:inputText id="cp" value="#{direccionController.selected.cp}" title="#{bundle.EditDireccionTitle_cp}" />
                    <h:outputLabel value="#{bundle.EditDireccionLabel_esProvId}" for="esProvId" />
                    <h:selectOneMenu id="esProvId" value="#{direccionController.selected.esProvId}" title="#{bundle.EditDireccionTitle_esProvId}" >
                        <f:selectItems value="#{esProvController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditDireccionLabel_direccionTypeId}" for="direccionTypeId" />
                    <h:selectOneMenu id="direccionTypeId" value="#{direccionController.selected.direccionTypeId}" title="#{bundle.EditDireccionTitle_direccionTypeId}" >
                        <f:selectItems value="#{direccionTypeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditDireccionLabel_alumnoId}" for="alumnoId" />
                    <h:selectOneMenu id="alumnoId" value="#{direccionController.selected.alumnoId}" title="#{bundle.EditDireccionTitle_alumnoId}" >
                        <f:selectItems value="#{alumnoController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{direccionController.update}" value="#{bundle.EditDireccionSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditDireccionViewLink}"/>
                <br />
                <h:commandLink action="#{direccionController.prepareList}" value="#{bundle.EditDireccionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditDireccionIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/direccion/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListDireccionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListDireccionEmpty}" rendered="#{direccionController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{direccionController.items.rowCount > 0}">
                    <h:outputText value="#{direccionController.pagination.pageFirstItem + 1}..#{direccionController.pagination.pageLastItem + 1}/#{direccionController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{direccionController.previous}" value="#{bundle.Previous} #{direccionController.pagination.pageSize}" rendered="#{direccionController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{direccionController.next}" value="#{bundle.Next} #{direccionController.pagination.pageSize}" rendered="#{direccionController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{direccionController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_direccionId}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccionId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_direcLinea1}"/>
                            </f:facet>
                            <h:outputText value="#{item.direcLinea1}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_direcLinea2}"/>
                            </f:facet>
                            <h:outputText value="#{item.direcLinea2}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_ciudad}"/>
                            </f:facet>
                            <h:outputText value="#{item.ciudad}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_cp}"/>
                            </f:facet>
                            <h:outputText value="#{item.cp}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_esProvId}"/>
                            </f:facet>
                            <h:outputText value="#{item.esProvId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_direccionTypeId}"/>
                            </f:facet>
                            <h:outputText value="#{item.direccionTypeId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDireccionTitle_alumnoId}"/>
                            </f:facet>
                            <h:outputText value="#{item.alumnoId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{direccionController.prepareView}" value="#{bundle.ListDireccionViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{direccionController.prepareEdit}" value="#{bundle.ListDireccionEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{direccionController.destroy}" value="#{bundle.ListDireccionDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{direccionController.prepareCreate}" value="#{bundle.ListDireccionCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListDireccionIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/direccion/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewDireccionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewDireccionLabel_direccionId}"/>
                    <h:outputText value="#{direccionController.selected.direccionId}" title="#{bundle.ViewDireccionTitle_direccionId}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_direcLinea1}"/>
                    <h:outputText value="#{direccionController.selected.direcLinea1}" title="#{bundle.ViewDireccionTitle_direcLinea1}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_direcLinea2}"/>
                    <h:outputText value="#{direccionController.selected.direcLinea2}" title="#{bundle.ViewDireccionTitle_direcLinea2}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_ciudad}"/>
                    <h:outputText value="#{direccionController.selected.ciudad}" title="#{bundle.ViewDireccionTitle_ciudad}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_cp}"/>
                    <h:outputText value="#{direccionController.selected.cp}" title="#{bundle.ViewDireccionTitle_cp}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_esProvId}"/>
                    <h:outputText value="#{direccionController.selected.esProvId}" title="#{bundle.ViewDireccionTitle_esProvId}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_direccionTypeId}"/>
                    <h:outputText value="#{direccionController.selected.direccionTypeId}" title="#{bundle.ViewDireccionTitle_direccionTypeId}"/>
                    <h:outputText value="#{bundle.ViewDireccionLabel_alumnoId}"/>
                    <h:outputText value="#{direccionController.selected.alumnoId}" title="#{bundle.ViewDireccionTitle_alumnoId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{direccionController.destroyAndView}" value="#{bundle.ViewDireccionDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewDireccionEditLink}"/>
                <br />
                <h:commandLink action="#{direccionController.prepareCreate}" value="#{bundle.ViewDireccionCreateLink}" />
                <br />
                <h:commandLink action="#{direccionController.prepareList}" value="#{bundle.ViewDireccionShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewDireccionIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>